(window["webpackJsonp"]=window["webpackJsonp"]||[]).push([[13],{"./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./src/client/components/layout/Layout.vue?vue&type=script&lang=js&":/*!********************************************************************************************************************************************************************!*\
!*** ./node_modules/babel-loader/lib??ref--1!./node_modules/vue-loader/lib??vue-loader-options!./src/client/components/layout/Layout.vue?vue&type=script&lang=js& ***!
\********************************************************************************************************************************************************************//*!exports provided: default*/(function(module,__webpack_exports__,__webpack_require__){"use strict";__webpack_require__.r(__webpack_exports__);var client_components_layout_HeaderLayout_vue__WEBPACK_IMPORTED_MODULE_0__=__webpack_require__(/*!client/components/layout/HeaderLayout.vue*/"./src/client/components/layout/HeaderLayout.vue");var client_components_layout_FooterLayout_vue__WEBPACK_IMPORTED_MODULE_1__=__webpack_require__(/*!client/components/layout/FooterLayout.vue*/"./src/client/components/layout/FooterLayout.vue");__webpack_exports__["default"]=({name:"Layout",components:{"HeaderLayout":client_components_layout_HeaderLayout_vue__WEBPACK_IMPORTED_MODULE_0__["default"],"FooterLayout":client_components_layout_FooterLayout_vue__WEBPACK_IMPORTED_MODULE_1__["default"]},computed:{screenHeight:function screenHeight(){return this.$store.state.global.screenHeight;},screenWidth:function screenWidth(){return this.$store.state.global.screenWidth;}},mounted:function mounted(){var _this=this;if(typeof window==="undefined")return;this.$store.dispatch('GLOBAL_SCREEN',{screenHeight:window.innerHeight,screenWidth:window.innerWidth});this.changeFullSectionHeight();document.body.style.backgroundColor='#000';this.fullHeightSectionOnMobile(document.getElementById("aboutSection"),768);this.fullHeightSectionOnMobile(document.getElementById("coinDistributionSection"),768);this.addEvent(window,"resize",function(event){if(_this.$store.state.global.screenWidth==window.innerWidth){return;}else{_this.$store.dispatch('GLOBAL_SCREEN',{screenHeight:window.innerHeight,screenWidth:window.innerWidth});_this.changeFullSectionHeight();}});},methods:{changeFullSectionHeight:function changeFullSectionHeight(){var fullSection=document.getElementsByClassName('fullSection');var fullSectionHeight=this.screenHeight-70;for(var i=0;i<fullSection.length;i++){fullSection[i].style.height=fullSectionHeight+'px';}
this.fullHeightSectionOnMobile(document.getElementById("aboutSection"),768);this.fullHeightSectionOnMobile(document.getElementById("coinDistributionSection"),768);},fullHeightSectionOnMobile:function fullHeightSectionOnMobile(element,maxWidth){if(element===undefined||element===null)return;if(this.screenWidth<=maxWidth){element.firstChild.className+=" fullHeight";element.setAttribute('style','height:auto !important');}else element.firstChild.className=element.firstChild.className.replace("fullHeight","");},addEvent:function addEvent(object,type,callback){if(object===null||typeof object==='undefined')return;if(object.addEventListener){object.addEventListener(type,callback,false);}else if(object.attachEvent){object.attachEvent("on"+type,callback);}else{object["on"+type]=callback;}}}});}),"./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./src/client/pages/ClearIndexedDB.page.vue?vue&type=script&lang=js&":/*!*********************************************************************************************************************************************************************!*\
!*** ./node_modules/babel-loader/lib??ref--1!./node_modules/vue-loader/lib??vue-loader-options!./src/client/pages/ClearIndexedDB.page.vue?vue&type=script&lang=js& ***!
\*********************************************************************************************************************************************************************//*!exports provided: default*/(function(module,__webpack_exports__,__webpack_require__){"use strict";__webpack_require__.r(__webpack_exports__);var client_components_layout_Layout_vue__WEBPACK_IMPORTED_MODULE_0__=__webpack_require__(/*!client/components/layout/Layout.vue*/"./src/client/components/layout/Layout.vue");__webpack_exports__["default"]=({name:"transactions-page",components:{"layout":client_components_layout_Layout_vue__WEBPACK_IMPORTED_MODULE_0__["default"]},methods:{clearIndexedDB:function clearIndexedDB(){window.indexedDB.deleteDatabase('_pouch_validateDB');window.indexedDB.deleteDatabase('_pouch_defaultDB');window.indexedDB.deleteDatabase('_pouch_walletDB');window.indexedDB.deleteDatabase('_pouch_blockchainDB3');window.indexedDB.deleteDatabase('_pouch_blockchainDB2');window.indexedDB.deleteDatabase('_pouch_blockchainDB');window.localStorage.removeItem("_pouch_check_localstorage");window.localStorage.removeItem("_pouch_validateDB");window.localStorage.removeItem("_pouch_defaultDB");window.localStorage.removeItem("_pouch_blockchainDB3");window.localStorage.removeItem("_pouch_blockchainDB2");window.localStorage.removeItem("_pouch_validateDB");window.localStorage.removeItem("_pouch_walletDB");alert("The indexedDB was cleared!");this.getAllIndexedDBs();},getAllIndexedDBs:function getAllIndexedDBs(){window.indexedDB.webkitGetDatabaseNames().onsuccess=function(sender,args){var r=sender.target.result;for(var i in r){indexedDB.deleteDatabase(r[i]);}};}}});}),"./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/vue-loader/lib/index.js?!./src/client/components/layout/Layout.vue?vue&type=template&id=5ca12291&":/*!**************************************************************************************************************************************************************************************************************!*\
!*** ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/client/components/layout/Layout.vue?vue&type=template&id=5ca12291& ***!
\**************************************************************************************************************************************************************************************************************//*!exports provided: render, staticRenderFns*/(function(module,__webpack_exports__,__webpack_require__){"use strict";__webpack_require__.r(__webpack_exports__);__webpack_require__.d(__webpack_exports__,"render",function(){return render;});__webpack_require__.d(__webpack_exports__,"staticRenderFns",function(){return staticRenderFns;});var render=function(){var _vm=this
var _h=_vm.$createElement
var _c=_vm._self._c||_h
return _c("div",{staticStyle:{"overflow-y":"auto"}},[_c("HeaderLayout"),_vm._v(" "),_vm._m(0),_vm._v(" "),_c("div",{attrs:{id:"websiteBody"}},[_vm._t("content")],2),_vm._v(" "),_c("FooterLayout")],1)}
var staticRenderFns=[function(){var _vm=this
var _h=_vm.$createElement
var _c=_vm._self._c||_h
return _c("div",{staticClass:"backgroundVideoWrap"},[_c("video",{staticClass:"backgroundVideo",attrs:{autoplay:"",loop:""}},[_c("source",{attrs:{src:"public/assets/video/file.mp4",type:"video/mp4"}})])])}]
render._withStripped=true}),"./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/vue-loader/lib/index.js?!./src/client/pages/ClearIndexedDB.page.vue?vue&type=template&id=ab7dd176&":/*!***************************************************************************************************************************************************************************************************************!*\
!*** ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/client/pages/ClearIndexedDB.page.vue?vue&type=template&id=ab7dd176& ***!
\***************************************************************************************************************************************************************************************************************//*!exports provided: render, staticRenderFns*/(function(module,__webpack_exports__,__webpack_require__){"use strict";__webpack_require__.r(__webpack_exports__);__webpack_require__.d(__webpack_exports__,"render",function(){return render;});__webpack_require__.d(__webpack_exports__,"staticRenderFns",function(){return staticRenderFns;});var render=function(){var _vm=this
var _h=_vm.$createElement
var _c=_vm._self._c||_h
return _c("layout",[_c("div",{attrs:{slot:"content"},slot:"content"},[_c("div",{staticStyle:{"margin-top":"200px","margin-left":"100px","margin-bottom":"900px"}},[_c("button",{staticStyle:{"background-color":"yellow",height:"100px"},on:{click:_vm.clearIndexedDB}},[_vm._v("Clear IndexedDB")])])])])}
var staticRenderFns=[]
render._withStripped=true}),"./src/client/components/layout/Layout.vue":/*!*************************************************!*\
!*** ./src/client/components/layout/Layout.vue ***!
\*************************************************//*!exports provided: default*/(function(module,__webpack_exports__,__webpack_require__){"use strict";__webpack_require__.r(__webpack_exports__);var _Layout_vue_vue_type_template_id_5ca12291___WEBPACK_IMPORTED_MODULE_0__=__webpack_require__(/*!./Layout.vue?vue&type=template&id=5ca12291&*/"./src/client/components/layout/Layout.vue?vue&type=template&id=5ca12291&");var _Layout_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_1__=__webpack_require__(/*!./Layout.vue?vue&type=script&lang=js&*/"./src/client/components/layout/Layout.vue?vue&type=script&lang=js&");var _node_modules_vue_loader_lib_runtime_componentNormalizer_js__WEBPACK_IMPORTED_MODULE_2__=__webpack_require__(/*!../../../../node_modules/vue-loader/lib/runtime/componentNormalizer.js*/"./node_modules/vue-loader/lib/runtime/componentNormalizer.js");var component=Object(_node_modules_vue_loader_lib_runtime_componentNormalizer_js__WEBPACK_IMPORTED_MODULE_2__["default"])(_Layout_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_1__["default"],_Layout_vue_vue_type_template_id_5ca12291___WEBPACK_IMPORTED_MODULE_0__["render"],_Layout_vue_vue_type_template_id_5ca12291___WEBPACK_IMPORTED_MODULE_0__["staticRenderFns"],false,null,null,null)
if(false){var api;}
component.options.__file="src/client/components/layout/Layout.vue"
__webpack_exports__["default"]=(component.exports);}),"./src/client/components/layout/Layout.vue?vue&type=script&lang=js&":/*!**************************************************************************!*\
!*** ./src/client/components/layout/Layout.vue?vue&type=script&lang=js& ***!
\**************************************************************************//*!exports provided: default*/(function(module,__webpack_exports__,__webpack_require__){"use strict";__webpack_require__.r(__webpack_exports__);var _node_modules_babel_loader_lib_index_js_ref_1_node_modules_vue_loader_lib_index_js_vue_loader_options_Layout_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_0__=__webpack_require__(/*!-!../../../../node_modules/babel-loader/lib??ref--1!../../../../node_modules/vue-loader/lib??vue-loader-options!./Layout.vue?vue&type=script&lang=js&*/"./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./src/client/components/layout/Layout.vue?vue&type=script&lang=js&");__webpack_exports__["default"]=(_node_modules_babel_loader_lib_index_js_ref_1_node_modules_vue_loader_lib_index_js_vue_loader_options_Layout_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_0__["default"]);}),"./src/client/components/layout/Layout.vue?vue&type=template&id=5ca12291&":/*!********************************************************************************!*\
!*** ./src/client/components/layout/Layout.vue?vue&type=template&id=5ca12291& ***!
\********************************************************************************//*!exports provided: render, staticRenderFns*/(function(module,__webpack_exports__,__webpack_require__){"use strict";__webpack_require__.r(__webpack_exports__);var _node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_vue_loader_lib_index_js_vue_loader_options_Layout_vue_vue_type_template_id_5ca12291___WEBPACK_IMPORTED_MODULE_0__=__webpack_require__(/*!-!../../../../node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!../../../../node_modules/vue-loader/lib??vue-loader-options!./Layout.vue?vue&type=template&id=5ca12291&*/"./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/vue-loader/lib/index.js?!./src/client/components/layout/Layout.vue?vue&type=template&id=5ca12291&");__webpack_require__.d(__webpack_exports__,"render",function(){return _node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_vue_loader_lib_index_js_vue_loader_options_Layout_vue_vue_type_template_id_5ca12291___WEBPACK_IMPORTED_MODULE_0__["render"];});__webpack_require__.d(__webpack_exports__,"staticRenderFns",function(){return _node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_vue_loader_lib_index_js_vue_loader_options_Layout_vue_vue_type_template_id_5ca12291___WEBPACK_IMPORTED_MODULE_0__["staticRenderFns"];});}),"./src/client/pages/ClearIndexedDB.page.vue":/*!**************************************************!*\
!*** ./src/client/pages/ClearIndexedDB.page.vue ***!
\**************************************************//*!exports provided: default*/(function(module,__webpack_exports__,__webpack_require__){"use strict";__webpack_require__.r(__webpack_exports__);var _ClearIndexedDB_page_vue_vue_type_template_id_ab7dd176___WEBPACK_IMPORTED_MODULE_0__=__webpack_require__(/*!./ClearIndexedDB.page.vue?vue&type=template&id=ab7dd176&*/"./src/client/pages/ClearIndexedDB.page.vue?vue&type=template&id=ab7dd176&");var _ClearIndexedDB_page_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_1__=__webpack_require__(/*!./ClearIndexedDB.page.vue?vue&type=script&lang=js&*/"./src/client/pages/ClearIndexedDB.page.vue?vue&type=script&lang=js&");var _node_modules_vue_loader_lib_runtime_componentNormalizer_js__WEBPACK_IMPORTED_MODULE_2__=__webpack_require__(/*!../../../node_modules/vue-loader/lib/runtime/componentNormalizer.js*/"./node_modules/vue-loader/lib/runtime/componentNormalizer.js");var component=Object(_node_modules_vue_loader_lib_runtime_componentNormalizer_js__WEBPACK_IMPORTED_MODULE_2__["default"])(_ClearIndexedDB_page_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_1__["default"],_ClearIndexedDB_page_vue_vue_type_template_id_ab7dd176___WEBPACK_IMPORTED_MODULE_0__["render"],_ClearIndexedDB_page_vue_vue_type_template_id_ab7dd176___WEBPACK_IMPORTED_MODULE_0__["staticRenderFns"],false,null,null,null)
if(false){var api;}
component.options.__file="src/client/pages/ClearIndexedDB.page.vue"
__webpack_exports__["default"]=(component.exports);}),"./src/client/pages/ClearIndexedDB.page.vue?vue&type=script&lang=js&":/*!***************************************************************************!*\
!*** ./src/client/pages/ClearIndexedDB.page.vue?vue&type=script&lang=js& ***!
\***************************************************************************//*!exports provided: default*/(function(module,__webpack_exports__,__webpack_require__){"use strict";__webpack_require__.r(__webpack_exports__);var _node_modules_babel_loader_lib_index_js_ref_1_node_modules_vue_loader_lib_index_js_vue_loader_options_ClearIndexedDB_page_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_0__=__webpack_require__(/*!-!../../../node_modules/babel-loader/lib??ref--1!../../../node_modules/vue-loader/lib??vue-loader-options!./ClearIndexedDB.page.vue?vue&type=script&lang=js&*/"./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./src/client/pages/ClearIndexedDB.page.vue?vue&type=script&lang=js&");__webpack_exports__["default"]=(_node_modules_babel_loader_lib_index_js_ref_1_node_modules_vue_loader_lib_index_js_vue_loader_options_ClearIndexedDB_page_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_0__["default"]);}),"./src/client/pages/ClearIndexedDB.page.vue?vue&type=template&id=ab7dd176&":/*!*********************************************************************************!*\
!*** ./src/client/pages/ClearIndexedDB.page.vue?vue&type=template&id=ab7dd176& ***!
\*********************************************************************************//*!exports provided: render, staticRenderFns*/(function(module,__webpack_exports__,__webpack_require__){"use strict";__webpack_require__.r(__webpack_exports__);var _node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_vue_loader_lib_index_js_vue_loader_options_ClearIndexedDB_page_vue_vue_type_template_id_ab7dd176___WEBPACK_IMPORTED_MODULE_0__=__webpack_require__(/*!-!../../../node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!../../../node_modules/vue-loader/lib??vue-loader-options!./ClearIndexedDB.page.vue?vue&type=template&id=ab7dd176&*/"./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/vue-loader/lib/index.js?!./src/client/pages/ClearIndexedDB.page.vue?vue&type=template&id=ab7dd176&");__webpack_require__.d(__webpack_exports__,"render",function(){return _node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_vue_loader_lib_index_js_vue_loader_options_ClearIndexedDB_page_vue_vue_type_template_id_ab7dd176___WEBPACK_IMPORTED_MODULE_0__["render"];});__webpack_require__.d(__webpack_exports__,"staticRenderFns",function(){return _node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_vue_loader_lib_index_js_vue_loader_options_ClearIndexedDB_page_vue_vue_type_template_id_ab7dd176___WEBPACK_IMPORTED_MODULE_0__["staticRenderFns"];});})}]);